<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Vue App</title>
    <!-- Link to compiled CSS file (generated by Vue build process) -->
    <link href="/vue-assets/css/app.css" rel="stylesheet">
</head>
<body>
    <div id="app"></div> <!-- Root element where Vue.js will mount -->

    <!-- Include the compiled Vue.js script (generated by Vue build process) -->
    <script src="/vue-assets/js/app.js"></script>
</body>
</html>
